### ISSUE TITLE
JSON 파싱 실패했을 때 500에러 발생

### ISSUE THREAD

**Issue by wlsh44** [Best-House/rms-was#38]
- 원자재 생성 api에서 defaultUnitPrice 필드에 문자를 넣을 때 400 에러가 아닌 500 에러 발생

<img width="622" alt="image" src="https://github.com/Best-House/rms-was/assets/49276666/c71b33f9-1a27-4e68-8e76-2a6acac4f016">

**Comment by hjsung809** [comment]
원하는대로 코드 작성해서 PR만들어주면 감사하겠습니당
